name: Firmware Selector Test

on:
  push:
    paths:
      - ".github/workflows/*"
      - "www/**"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: www/
        css: true

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: |
        yarn install
        yarn prettier --check www
        yarn eslint www/

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-playwright pytest-simplehttpserver

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    - name: Run your tests
      run: pytest --tracing=retain-on-failure --simplehttpserver-directory ./www/

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-traces
        path: test-results/
